import type { InkletRequestOptions } from "./client.js";
import {
  delay,
  expectEnum,
  throwIfAborted,
  validateEnumOption,
  validateWaitNumber,
} from "./contents.js";
import {
  ConfigurationError,
  ConflictError,
  InvalidResponseError,
  NetworkError,
  OperationAbortedError,
} from "./errors.js";
import {
  SDK_API_PREFIX,
  encodePathSegment,
  expectBoolean,
  expectRecord,
  expectRecordArray,
  expectString,
  validateLimit,
  type ResourceTransport,
} from "./resource.js";
import type { AnalysisState } from "./analyses.js";

export type AnalysisEventLevel = "info" | "warn" | "error";

/** `agent` events come from the model loop; `backend` events from Inklet. */
export type AnalysisEventSource = "agent" | "backend";

/**
 * Verbatim agent payload. Only present on `agent` events read with
 * `detail: "full"`, which the backend allows once the Analysis is terminal.
 */
export interface AnalysisEventDetail {
  /** Tool-call arguments, as sent by the agent. */
  input?: unknown;
  /** Tool result body. */
  output?: string;
  /** `true` when the tool call reported a failure. */
  isError?: boolean;
  /** Assistant text for `assistant.note` and similar events. */
  text?: string;
}

/**
 * One entry in an Analysis event stream.
 *
 * `type` is an open set: the SDK parses unknown types instead of rejecting
 * them, so a backend that starts emitting a new event type never breaks an
 * older SDK. Switch on the types you know and fall back to `summary`, which
 * the backend always supplies as a single ready-to-display sentence.
 *
 * Known types: `analysis.created`, `analysis.dispatched`, `analysis.leased`,
 * `analysis.lease_expired`, `analysis.completed`, `analysis.failed`,
 * `context.materialized`, `kernel.selected`, `turn.started`, `turn.ended`,
 * `tool.called`, `tool.finished`, `assistant.note`, `plan.validated`,
 * `plan.submitted`, `plan.accepted`, `plan.rejected`, `render.finished`,
 * `render.failed`, `delivery.published`, `delivery.confirmed`,
 * `delivery.failed`.
 */
export interface AnalysisEvent {
  /** Monotonic per Analysis. Use it as `after` to resume. */
  seq: number;
  at: string;
  /** Which execution attempt produced the event; retries restart the agent. */
  attempt: number;
  source: AnalysisEventSource;
  type: string;
  level: AnalysisEventLevel;
  /** A displayable one-line summary generated by the backend. */
  summary: string;
  /** Structured, type-specific fields. Empty when the event carries none. */
  data: Record<string, unknown>;
  /** `null` unless the page was read with `detail: "full"`. */
  detail: AnalysisEventDetail | null;
}

export interface AnalysisEventPage {
  items: readonly AnalysisEvent[];
  /** Pass back as `after` to read the next page; `null` at the end. */
  nextAfter: number | null;
  hasMore: boolean;
  /** The Analysis state when the page was produced. */
  state: AnalysisState;
}

export interface ListAnalysisEventsOptions {
  /** Exclusive lower bound: only events with a greater `seq` are returned. */
  after?: number;
  /** 1-200. The backend picks a default when omitted. */
  limit?: number;
  /**
   * `full` adds `detail` to agent events and is only available once the
   * Analysis is `completed` or `failed`; earlier it is a `ConflictError` with
   * `code: "analysis_in_progress"`.
   */
  detail?: AnalysisEventDetailLevel;
}

export type AnalysisEventDetailLevel = "summary" | "full";

export interface WatchAnalysisOptions {
  /** Resume after this `seq` instead of replaying from the beginning. */
  after?: number;
  signal?: AbortSignal;
  /**
   * Poll interval for the `listEvents` fallback used when the response is not
   * `text/event-stream`. Defaults to 1,000 ms.
   */
  pollIntervalMs?: number;
  /**
   * Delay before the first reconnect attempt, doubled for each further
   * attempt and capped at five attempts. Defaults to 500 ms.
   */
  reconnectDelayMs?: number;
}

export interface TimelineOptions {
  /** Defaults to `summary`. `full` requires a terminal Analysis. */
  detail?: AnalysisEventDetailLevel;
  /** Events per request, 1-200. Defaults to 100. */
  pageSize?: number;
  /** Start after this `seq` instead of at the first event. */
  after?: number;
  signal?: AbortSignal;
}

export interface AnalysisArchive {
  /** Short-lived download URL for the full run archive. */
  url: string;
  expiresAt: string;
}

const ANALYSIS_STATES = ["queued", "running", "completed", "failed"] as const;
const MAX_EVENT_LIMIT = 200;
const DEFAULT_TIMELINE_PAGE_SIZE = 100;
const WATCH_PAGE_LIMIT = MAX_EVENT_LIMIT;
const MAX_RECONNECT_ATTEMPTS = 5;
const MAX_RECONNECT_DELAY_MS = 30_000;
const WATCH_ABORTED = "Watching the Analysis event stream was aborted.";
const TIMELINE_ABORTED = "Reading the Analysis timeline was aborted.";

interface ResolvedWatchOptions {
  after: number | undefined;
  signal: AbortSignal | undefined;
  pollIntervalMs: number;
  reconnectDelayMs: number;
}

interface ResolvedTimelineOptions {
  after: number | undefined;
  signal: AbortSignal | undefined;
  detail: AnalysisEventDetailLevel;
  pageSize: number;
}

export async function listAnalysisEvents(
  transport: ResourceTransport,
  analysisId: string,
  options: ListAnalysisEventsOptions = {},
): Promise<AnalysisEventPage> {
  if (!options || typeof options !== "object") {
    throw new ConfigurationError("listEvents options must be an object.");
  }
  return fetchEventPage(
    transport,
    encodePathSegment(analysisId, "analysisId"),
    options,
  );
}

export function watchAnalysisEvents(
  transport: ResourceTransport,
  analysisId: string,
  options: WatchAnalysisOptions = {},
): AsyncIterable<AnalysisEvent> {
  if (!options || typeof options !== "object") {
    throw new ConfigurationError("watch options must be an object.");
  }
  const encodedId = encodePathSegment(analysisId, "analysisId");
  const resolved: ResolvedWatchOptions = {
    after: validateAfter(options.after),
    signal: options.signal,
    pollIntervalMs: validateWaitNumber(
      options.pollIntervalMs, 1_000, 100, 60_000, "pollIntervalMs",
    ),
    reconnectDelayMs: validateWaitNumber(
      options.reconnectDelayMs, 500, 10, 60_000, "reconnectDelayMs",
    ),
  };
  return streamAnalysisEvents(transport, encodedId, resolved);
}

export function analysisEventTimeline(
  transport: ResourceTransport,
  analysisId: string,
  options: TimelineOptions,
  readState: () => Promise<AnalysisState>,
): AsyncIterable<AnalysisEvent> {
  if (!options || typeof options !== "object") {
    throw new ConfigurationError("timeline options must be an object.");
  }
  const encodedId = encodePathSegment(analysisId, "analysisId");
  const detail = options.detail ?? "summary";
  validateEnumOption(detail, ["summary", "full"], "detail");
  const resolved: ResolvedTimelineOptions = {
    after: validateAfter(options.after),
    signal: options.signal,
    detail,
    pageSize:
      validateLimit(options.pageSize, MAX_EVENT_LIMIT) ??
      DEFAULT_TIMELINE_PAGE_SIZE,
  };
  return iterateTimeline(transport, encodedId, resolved, readState);
}

export async function retrieveAnalysisArchive(
  transport: ResourceTransport,
  analysisId: string,
): Promise<AnalysisArchive> {
  const encodedId = encodePathSegment(analysisId, "analysisId");
  const response = await transport.request(
    `${SDK_API_PREFIX}/analyses/${encodedId}/archive`,
  );
  const record = expectRecord(response);
  return {
    url: expectString(record, "url"),
    expiresAt: expectString(record, "expiresAt"),
  };
}

async function* streamAnalysisEvents(
  transport: ResourceTransport,
  encodedId: string,
  options: ResolvedWatchOptions,
): AsyncGenerator<AnalysisEvent, void, undefined> {
  let after = options.after;
  let attempt = 0;

  while (true) {
    throwIfAborted(options.signal, WATCH_ABORTED);

    let response: Response;
    try {
      response = await transport.requestRaw(
        streamPath(encodedId, after),
        streamRequestOptions(after, options.signal),
      );
    } catch (error) {
      throwIfAborted(options.signal, WATCH_ABORTED);
      if (!(error instanceof NetworkError)) {
        throw error;
      }
      attempt = await backOff(attempt, options, error);
      continue;
    }

    if (!isEventStream(response)) {
      // A proxy that cannot carry `text/event-stream` answered instead.
      await response.body?.cancel().catch(() => undefined);
      yield* pollAnalysisEvents(transport, encodedId, { ...options, after });
      return;
    }

    const body = response.body;
    if (body === null) {
      attempt = await backOff(attempt, options);
      continue;
    }

    const reader = body.getReader();
    const decoder = new SseDecoder();
    const text = new TextDecoder();
    let ended = false;

    try {
      while (!ended) {
        let chunk: Awaited<ReturnType<typeof reader.read>>;
        try {
          chunk = await reader.read();
        } catch (error) {
          throwIfAborted(options.signal, WATCH_ABORTED);
          if (error instanceof OperationAbortedError) {
            throw error;
          }
          break;
        }
        if (chunk.done) {
          break;
        }

        for (const message of decoder.push(text.decode(chunk.value, { stream: true }))) {
          attempt = 0;
          if (message.event === "end") {
            ended = true;
            break;
          }
          const event = parseAnalysisEvent(expectRecord(parseJson(message.data)));
          after = event.seq;
          yield event;
        }
      }
    } finally {
      await reader.cancel().catch(() => undefined);
    }

    if (ended) {
      return;
    }
    // The connection dropped before the Analysis reached a terminal state.
    attempt = await backOff(attempt, options);
  }
}

async function* pollAnalysisEvents(
  transport: ResourceTransport,
  encodedId: string,
  options: ResolvedWatchOptions,
): AsyncGenerator<AnalysisEvent, void, undefined> {
  let after = options.after;

  while (true) {
    throwIfAborted(options.signal, WATCH_ABORTED);
    const page = await fetchEventPage(transport, encodedId, {
      limit: WATCH_PAGE_LIMIT,
      ...(after === undefined ? {} : { after }),
    });
    for (const event of page.items) {
      after = event.seq;
      yield event;
    }
    if (page.nextAfter !== null) {
      after = page.nextAfter;
    }
    if (page.hasMore) {
      if (page.items.length === 0 && page.nextAfter === null) {
        // `hasMore` without a way to advance would spin forever.
        throw new InvalidResponseError();
      }
      continue;
    }
    if (isTerminalState(page.state)) {
      return;
    }
    await delay(options.pollIntervalMs, options.signal, WATCH_ABORTED);
  }
}

async function* iterateTimeline(
  transport: ResourceTransport,
  encodedId: string,
  options: ResolvedTimelineOptions,
  readState: () => Promise<AnalysisState>,
): AsyncGenerator<AnalysisEvent, void, undefined> {
  if (options.detail === "full") {
    // Fail before the first page rather than part way through the timeline.
    const state = await readState();
    if (!isTerminalState(state)) {
      throw new ConflictError(
        "Full Analysis event detail is only available once the Analysis has completed or failed.",
        { code: "analysis_in_progress", details: { state } },
      );
    }
  }

  let after = options.after;
  while (true) {
    throwIfAborted(options.signal, TIMELINE_ABORTED);
    const page = await fetchEventPage(transport, encodedId, {
      detail: options.detail,
      limit: options.pageSize,
      ...(after === undefined ? {} : { after }),
    });
    for (const event of page.items) {
      after = event.seq;
      yield event;
    }
    if (page.nextAfter !== null) {
      after = page.nextAfter;
    }
    if (!page.hasMore) {
      return;
    }
    if (page.items.length === 0 && page.nextAfter === null) {
      // `hasMore` without a way to advance would spin forever.
      throw new InvalidResponseError();
    }
  }
}

async function fetchEventPage(
  transport: ResourceTransport,
  encodedId: string,
  options: ListAnalysisEventsOptions,
): Promise<AnalysisEventPage> {
  const response = await transport.request(
    `${SDK_API_PREFIX}/analyses/${encodedId}/events${eventQuery(options)}`,
  );
  return parseAnalysisEventPage(response);
}

function eventQuery(options: ListAnalysisEventsOptions): string {
  const query = new URLSearchParams();
  const after = validateAfter(options.after);
  if (after !== undefined) {
    query.set("after", String(after));
  }
  const limit = validateLimit(options.limit, MAX_EVENT_LIMIT);
  if (limit !== undefined) {
    query.set("limit", String(limit));
  }
  if (options.detail !== undefined) {
    validateEnumOption(options.detail, ["summary", "full"], "detail");
    query.set("detail", options.detail);
  }
  return query.size === 0 ? "" : `?${query.toString()}`;
}

function streamPath(encodedId: string, after: number | undefined): string {
  const suffix = after === undefined ? "" : `?after=${after}`;
  return `${SDK_API_PREFIX}/analyses/${encodedId}/events/stream${suffix}`;
}

function streamRequestOptions(
  after: number | undefined,
  signal: AbortSignal | undefined,
): InkletRequestOptions {
  const headers = new Headers({ accept: "text/event-stream" });
  if (after !== undefined) {
    // Honoured by the backend on reconnect, and by any conforming SSE proxy.
    headers.set("last-event-id", String(after));
  }
  const options: InkletRequestOptions = { method: "GET", headers };
  if (signal !== undefined) {
    options.signal = signal;
  }
  return options;
}

async function backOff(
  attempt: number,
  options: ResolvedWatchOptions,
  cause?: Error,
): Promise<number> {
  const next = attempt + 1;
  if (next > MAX_RECONNECT_ATTEMPTS) {
    throw (
      cause ??
      new NetworkError(
        `The Analysis event stream disconnected and could not be resumed after ${MAX_RECONNECT_ATTEMPTS} attempts.`,
      )
    );
  }
  await delay(
    Math.min(options.reconnectDelayMs * 2 ** attempt, MAX_RECONNECT_DELAY_MS),
    options.signal,
    WATCH_ABORTED,
  );
  return next;
}

function isEventStream(response: Response): boolean {
  return (response.headers.get("content-type") ?? "")
    .toLowerCase()
    .includes("text/event-stream");
}

function isTerminalState(state: AnalysisState): boolean {
  return state === "completed" || state === "failed";
}

function validateAfter(value: number | undefined): number | undefined {
  if (value === undefined) {
    return undefined;
  }
  if (!Number.isInteger(value) || value < 0) {
    throw new ConfigurationError(
      "after must be a non-negative integer event sequence number.",
    );
  }
  return value;
}

function parseJson(value: string): unknown {
  try {
    return JSON.parse(value);
  } catch (cause) {
    throw new InvalidResponseError({ cause });
  }
}

export function parseAnalysisEventPage(value: unknown): AnalysisEventPage {
  const record = expectRecord(value);
  return {
    items: expectRecordArray(record.items).map(parseAnalysisEvent),
    nextAfter: nullableSequence(record.nextAfter ?? null),
    hasMore: expectBoolean(record, "hasMore"),
    state: expectEnum(record.state, ANALYSIS_STATES),
  };
}

export function parseAnalysisEvent(
  record: Record<string, unknown>,
): AnalysisEvent {
  const summary = record.summary;
  if (typeof summary !== "string") {
    throw new InvalidResponseError();
  }
  return {
    seq: expectSequence(record, "seq"),
    at: expectString(record, "at"),
    attempt: expectSequence(record, "attempt"),
    source: expectEnum(record.source, ["agent", "backend"] as const),
    // Deliberately any non-empty string: new event types must not break reads.
    type: expectString(record, "type"),
    level: expectEnum(record.level, ["info", "warn", "error"] as const),
    summary,
    data: parseEventData(record.data),
    detail: parseEventDetail(record.detail ?? null),
  };
}

function parseEventData(value: unknown): Record<string, unknown> {
  if (value === undefined || value === null) {
    return {};
  }
  return { ...expectRecord(value) };
}

function parseEventDetail(value: unknown): AnalysisEventDetail | null {
  if (value === undefined || value === null) {
    return null;
  }
  const record = expectRecord(value);
  const detail: AnalysisEventDetail = {};
  if (record.input !== undefined) {
    detail.input = record.input;
  }
  const output = optionalString(record.output);
  if (output !== undefined) {
    detail.output = output;
  }
  if (record.isError !== undefined && record.isError !== null) {
    if (typeof record.isError !== "boolean") {
      throw new InvalidResponseError();
    }
    detail.isError = record.isError;
  }
  const text = optionalString(record.text);
  if (text !== undefined) {
    detail.text = text;
  }
  return detail;
}

function optionalString(value: unknown): string | undefined {
  if (value === undefined || value === null) {
    return undefined;
  }
  if (typeof value !== "string") {
    throw new InvalidResponseError();
  }
  return value;
}

function expectSequence(record: Record<string, unknown>, key: string): number {
  const value = record[key];
  if (typeof value !== "number" || !Number.isInteger(value) || value < 0) {
    throw new InvalidResponseError();
  }
  return value;
}

function nullableSequence(value: unknown): number | null {
  if (value === null) {
    return null;
  }
  if (typeof value !== "number" || !Number.isInteger(value) || value < 0) {
    throw new InvalidResponseError();
  }
  return value;
}

interface SseMessage {
  id: string | null;
  event: string | null;
  data: string;
}

/**
 * Incremental `text/event-stream` decoder.
 *
 * Chunks arrive at arbitrary boundaries, so lines are buffered until a
 * terminator is seen; a trailing lone `\r` is held back because it may still
 * turn out to be the first half of a `\r\n`. Comment lines (`: ping`) are
 * dropped, `data:` lines accumulate and are joined with newlines, and an event
 * is only dispatched on a blank line, per the HTML spec.
 */
class SseDecoder {
  #buffer = "";
  #data: string[] = [];
  #event: string | null = null;
  #lastId: string | null = null;

  push(chunk: string): SseMessage[] {
    if (chunk.length === 0) {
      return [];
    }
    this.#buffer += chunk;
    const messages: SseMessage[] = [];

    while (true) {
      const boundary = nextLineBoundary(this.#buffer);
      if (boundary === null) {
        break;
      }
      const line = this.#buffer.slice(0, boundary.end);
      this.#buffer = this.#buffer.slice(boundary.next);
      const message = this.#consume(line);
      if (message !== null) {
        messages.push(message);
      }
    }

    return messages;
  }

  #consume(line: string): SseMessage | null {
    if (line.length === 0) {
      return this.#dispatch();
    }
    if (line.startsWith(":")) {
      return null;
    }

    const colon = line.indexOf(":");
    const field = colon === -1 ? line : line.slice(0, colon);
    let value = colon === -1 ? "" : line.slice(colon + 1);
    if (value.startsWith(" ")) {
      value = value.slice(1);
    }

    switch (field) {
      case "event":
        this.#event = value;
        break;
      case "data":
        this.#data.push(value);
        break;
      case "id":
        if (!value.includes(" ")) {
          this.#lastId = value;
        }
        break;
      default:
        break;
    }
    return null;
  }

  #dispatch(): SseMessage | null {
    const data = this.#data;
    const event = this.#event;
    this.#data = [];
    this.#event = null;
    if (data.length === 0) {
      return null;
    }
    return { id: this.#lastId, event, data: data.join("\n") };
  }
}

function nextLineBoundary(
  buffer: string,
): { end: number; next: number } | null {
  const lf = buffer.indexOf("\n");
  const cr = buffer.indexOf("\r");

  if (cr !== -1 && (lf === -1 || cr < lf)) {
    if (cr === buffer.length - 1) {
      // Could still become "\r\n" once the next chunk arrives.
      return null;
    }
    return buffer[cr + 1] === "\n"
      ? { end: cr, next: cr + 2 }
      : { end: cr, next: cr + 1 };
  }
  if (lf !== -1) {
    return { end: lf, next: lf + 1 };
  }
  return null;
}
